language: spanish
username: admin

overview_dashboards:
    num_panel_per_row: 1
    panel_height: 2
    panel_weight: 10
    panel_type: stat  #It can be [gauge, stat]
    thresholds:
        warning: 700
        caution: 1000

messages:

    english:
        device_dashboard:
            CO2:
                title: 'CO2 ppm'
                description:
                - 'CO2 concentration in '
                - ' measured by device '
            temperature:
                title: 'Temperature ºC'
                description:
                - 'Temperature in '
                - ' measured by device '
            humidity:
                title: 'Humidity %'
                description:
                - 'Humidity in '
                - ' measured by device '
        overview_dashboard:
            title: 'General'
            link: 'Go to '
        detail_dashboard:
            title: 'Detail'

    spanish:
        device_dashboard:
            CO2:
                title: 'CO2 ppm'
                description:
                - 'Concentración de CO2 en '
                - ' medido por el dispositivo '
            temperature:
                title: 'Temperatura ºC'
                description:
                - 'Temperatura en '
                - ' medida por el dispositivo '
            humidity:
                title: 'Humedad %'
                description:
                - 'Humedad en '
                - ' medida por el dispositivo '
        overview_dashboard:
            title: 'General'
            link: 'Ir a '
        detail_dashboard:
            title: 'Detalle'
