{
 "title": "Detalle",
 "tags": [ "sensor" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "uid" }
  ]
 },
 "panels": [
  {
   "title": "CO2 ppm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "expr": "CO2{exported_job=\"$uid\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Temperatura ºC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "Temperature{exported_job=\"$uid\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Humedad %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "Humidity{exported_job=\"$uid\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}