apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:7.4.1
          env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "{{ .Values.grafanaAdminPass }}"
          - name: GF_SERVER_ROOT_URL
          {{- if .Values.secondaryPublicIP }}
            value: "http://{{ .Values.secondaryPublicIP }}"
          {{- else }}
            value: "http://{{ .Values.publicIP }}"
          {{- end }}
          - name: GF_RENDERING_SERVER_URL
            value: "http://grafana-image-renderer-cip:8081/render"
          - name: GF_RENDERING_CALLBACK_URL
          {{- if .Values.secondaryPublicIP }}
            value: "http://{{ .Values.secondaryPublicIP }}/"
          {{- else }}
            value: "http://{{ .Values.publicIP }}/"
          {{- end }}
          - name: GF_LOG_FILTERS
            value: rendering:debug
          - name: GF_INSTALL_PLUGINS
            value: "cloudspout-button-panel"
          {{- if eq .Values.smtp_enabled true }}
          - name: GF_SMTP_ENABLED
            value: "{{ .Values.smtp_enabled }}"
          - name: GF_SMTP_HOST
            value: "{{ .Values.smtp_host }}"
          - name: GF_SMTP_USER
            value: "{{ .Values.smtp_user }}"
          - name: GF_SMTP_PASSWORD
            value: "{{ .Values.smtp_pass }}"
          - name: GF_SMTP_FROM_ADDRESS
            value: "{{ .Values.smtp_user }}"
          - name: GF_SMTP_FROM_NAME
            value: "{{ .Values.smtp_from }}"
          {{- end }}

          args:
          volumeMounts:
            - name: grafana-storage-volume
              mountPath: /var/lib/grafana/
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
          resources:
            {{- toYaml .Values.resources.grafana | nindent 12 }}
      volumes:
        - name: grafana-storage-volume
          hostPath:
            path: /data/grafana
            type: Directory
        - name: grafana-config
          configMap:
            name: grafana-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
data:
  datasource.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-cip:9090
        version: 1
        editable: true
        isDefault: true
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-np
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30300
