apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-image-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-image-renderer
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      containers:
        - name: grafana-image-renderer
          image: grafana/grafana-image-renderer:2.0.0-beta1
          env:
          - name: ENABLE_METRICS
            value: 'true'
          resources:
            {{- toYaml .Values.resources.grafanaimagerenderer | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer-cip
spec:
  type: NodePort
  selector:
    app: grafana-image-renderer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081