apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- (.Files.Glob "scripts/run.sh").AsConfig | nindent 2 }}
  {{- (.Files.Glob "scripts/emulate_sensor.py").AsConfig | nindent 2 }}